services:
  - type: web
    name: gps-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k gevent -w 1 app:app
    






